server:
  port: 9003
spring:
  application:
    name: obo_base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.34.145:3306/obo_qa?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
